### ISSUE TITLE
Not reading the configuration from application.yml file

### ISSUE THREAD

**Issue by skillet-loki** [miwurster/spring-data-influxdb#18]
When I tried to build the solution I am getting this error!

 ***************************\nAPPLICATION FAILED TO START\n***************************\n\n
Description:\n\nBinding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.influxdb' to org.springframework.data.influxdb.InfluxDBProperties failed:\n\n
 Property: spring.influxdb.retentionPolicy\n    Value: null\n    Reason: may not be empty\n\n 
 Property: spring.influxdb.url\n    Value: null\n    Reason: may not be empty\n\n  
 Property: spring.influxdb.username\n    Value: null\n    Reason: may not be empty\n\n  
 Property: spring.influxdb.database\n    Value: null\n    Reason: may not be empty\n\n\n
 Action:\n\nUpdate your application's configuration\n"

spring:
  application:
    name: xxxx
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#

  influxdb:
    url: xxxx:8086
    username: xxx
    password: xxx
    database: xxx
    retention-policy: autogen

I am new to this can you please help me @miwurster

**Comment by miwurster** [comment]
Are you sure your `application.yml` is well-formatted? 

Like this example?
```
spring:
  influxdb:
    url: http://localhost:8086
    username: user
    password: ~
    database: test
    retention-policy: autogen
    connect-timeout: 5
    read-timeout: 5
    write-timeout: 5
    gzip: true
```
