### ISSUE TITLE
Spring Data InfluxDB Does not Work With InfluxDB 1.*.*

### ISSUE THREAD

**Issue by schrieveslaach** [miwurster/spring-data-influxdb#3]
This Spring Data project does not work with InfluxDB 1.*.* versions. I tested this with the [official docker container](https://hub.docker.com/_/influxdb/).
I used following working `docker-compse.yml` file

```yaml
version: '2'
services:
  influxdb:
    image: influxdb:0.13.0-alpine
    ports:
     - "8086:8086"
  grafana:
    image: grafana/grafana:4.1.1
    ports:
     - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SECURITY_ADMIN_PASSWORD: secret
    links:
     - influxdb
```

When I create a dashboard in Grafana, InfluxDB returns data which I stored by the spring data plugin.

```java
        influxDBTemplate.createDatabase();

        Point p = Point.measurement("disk")
                .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                .tag("tenant", "default")
                .field("used", 90L)
                .field("free", 1L)
                .build();
        influxDBTemplate.write(p);
```
 But when I change to another InfluxDB version (e.g. influxdb:1.1.1-alpine) I can not create the database from code (c.f. `influxDBTemplate.createDatabase();`) - create must be performed by HTTP post, current version uses HTTP get. When I remove that line and create the database by hand (e.g. with `curl`), InfluxDB complains about `defaul rentation policy`.
